y=(9, 8.6, "Achieve")
print(type(y))
print(y[0])
print(y[1])
print(y[2])
print(type(y[0]))
print(type(y[1]))
print(type(y[2]))
print(y[-3])
print(y[-2])
print(y[-1])
print(type(y[-3]))
print(type(y[-2]))
print(type(y[-1]))
x=y+("pal", "python")
print(x)
print(x[2:5])
print(y[0:3])
print(len(x))
print(len(y))
ratings=(2,7,5,3,8,1,4,9)
ratingssorted=sorted(ratings)
print(ratingssorted)
nest=(1,2,("yam", "haha"),(45,67, (0,89)))
print(nest)
print(nest[0])
print(nest[1])
print(nest[2][0])
print(nest[2][1])
print(nest[3][0])
print(nest[3][1])
print(nest[3][2][0])
print(nest[3][2][1])
